[package]
name = "clicker"
version = "0.1.0"
authors = ["Mendelt Siebenga <msiebenga@lely.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
failure = "0.1.5"
serde = "1"
serde_derive = "1"
toml = "0.4.10"

[[bin]]
name = "click"
path = "src/main.rs"
